### ISSUE TITLE
Mostrar usuários do grupo

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#100]
Hoje não existe uma forma prática para ver os usuários que estão dentro de um grupo do Django admin.
Verificar se não existe uma forma já implementada do django admin que mostra os usuários contidos dentro do grupo, caso não exista então implementar essa possibilidade na pagina do grupo dentro da interface admin.

**Comment by gstvob** [comment]
da uma olhada no commit 9577b20, e vê se é isso mesmo.

![image](https://user-images.githubusercontent.com/18465203/47308232-686eb100-d607-11e8-8297-f219978e1d32.png)

**Comment by ramonrdm** [comment]
funcionando e testado
