### ISSUE TITLE
Fazer um template para o email

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#103]
Tem formas de usar um template de email para enviar emails.
Não somente usar strings.
Tem que rever como os emails estão sendo enviados e condensar essas operações em um lugar soh.

**Comment by gstvob** [comment]
feito, testei só no meu gmail, e a mensagem foi certinha, tem que ver se vai bem formatada nos outros também

**Comment by ramonrdm** [comment]
funcionando!
