### ISSUE TITLE
Mostrar locaveis por ordem alfabetica

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#105]
Na lista de locaveis dentro da pagina da unidade mostrar em ordem alfabetária.

**Comment by gstvob** [comment]
Tá mostrando agora, mas notei um problema, ele considera primeiro os que começam com letra maiúscula depois os com letra minúscula, ex: Totem de madeira vem antes de invisivel se o "i" estiver minúsculo, mas Invisivel vem antes do Totem de madeira, o "i" maiúsculo ali fez a diferença

**Comment by gstvob** [comment]
agora foi

**Comment by ramonrdm** [comment]
feito
