### ISSUE TITLE
String object do reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#108]
Colocar o objeto reserva com o 
def __ unicode __(self):
ou o __ str __
passando nome do locavel, quem pediu e atividade.
nos logs admin ta confuso olhar na lista

**Comment by gstvob** [comment]
![image](https://user-images.githubusercontent.com/18465203/47453162-68ef7f00-d7a2-11e8-832a-075cbe7feece.png)

Vê se é isso que tu tinha em mente

**Comment by ramonrdm** [comment]
exatamente isso
