### ISSUE TITLE
create objects na recorrencia

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#110]
Verificar onde estão sendo criados objetos e não é necessario. Pois estão sendo salvos no banco e tomando muito tempo.

**Comment by gstvob** [comment]
isso não cai no mesmo caso da issue anterior, que cria os Dummys lá
eu simplesmente troquei o .create() pra simplesmente chamar o modelo.

**Comment by ramonrdm** [comment]
issue anterior? cada coisa que leio aqui...
#109
