### ISSUE TITLE
qndo usuario cancela o resp recebe um email

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#112]
qndo usuario cancela o resp recebe um email 
mas o email eh como se tivesse feito uma nova reserva.
Fazer com que neste caso o email nao seja enviado.

**Comment by gstvob** [comment]
743c0e4 esse commit aqui já tinha resolvido isso, é o commit da issue 104

**Comment by ramonrdm** [comment]
precisamos testar na próxima reunião se o sistema online está mandado a mensagem correta para todas as trocas de estado.
