### ISSUE TITLE
Atualizar a dependencia do requests

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#116]
devido ao aviso:
https://github.com/ramonrdm/agendador/network/alert/requirements.txt/requests/open
temos que verificar se essa dependencia ainda eh necessaria e qual a versao mais atual podemos usar.

**Comment by gstvob** [comment]
link quebrado aqui

**Comment by ramonrdm** [comment]
era desnecessário, então retiramos.
