### ISSUE TITLE
Adicionar a possibilidade de busca na interface de admin

### ISSUE THREAD

**Issue by gstvob** [ramonrdm/agendador#125]
Colocar nos modelos de admin a possibilidade de busca.

**Comment by ramonrdm** [comment]
adicionar em filtro de buscas pelos logs do admin tbm

**Comment by ramonrdm** [comment]
perfect

**Comment by gstvob** [comment]
coloquei só filtro por usuário e flags de ação, precisa de mais algum?
os campos que têm são -> Tipo de conteudo (modelo), id do objeto, representação do objeto (__str__ do modelo), e a mensagem da ação (tipo, [{"changed": {"fields": ["periodo_limite"]}}])

**Comment by ramonrdm** [comment]
sim, Entradas De Log

**Comment by ramonrdm** [comment]
feito
