### ISSUE TITLE
Corrigir docker servindo templates e statics errados

### ISSUE THREAD

**Issue by gstvob** [ramonrdm/agendador#139]
Quando roda pelo docker. template de admin por exemplo não era pra ser o que está sendo carregado.

**Comment by ramonrdm** [comment]
templates dirs corrigidos, a prioridade eh q esta dentro do app agenda.
os statics tem que fazer um collectstatic toda vez que ficar alteração e então rodar pelo docker.

**Comment by ramonrdm** [comment]
verifica novamente os erros e templates envolvidos
