### ISSUE TITLE
locavel visivel

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#16]
só mostra locaveis que são visiveis.

**Comment by gabrieltron** [comment]
concluido

**Comment by ramonrdm** [comment]
deve aparacer para admins de unidades superiores ou admin do locavel.
isso tbm vale pra bloquado.

**Comment by gabrieltron** [comment]
isso apenas na parte de admin, certo? No index ele continua escondido, uma vez que, pelo menos por enquanto, o index é igual pra todos os usuários

**Comment by ramonrdm** [comment]
ok
