### ISSUE TITLE
só permitir agendar em locaveis não bloqueados

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#17]

**Comment by gabrieltron** [comment]
concluido

**Comment by ramonrdm** [comment]
se for root ou admin de unidades a cima pode reservar, se for admin do locavel tbm.

**Comment by gabrieltron** [comment]
é pra ele estar fazendo isso já, não sei dizer em qual commit weufha

**Comment by ramonrdm** [comment]
ok
