### ISSUE TITLE
verificar a permissoes de grupos antes de locar

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#18]
Verificar se está no grupo do locavel, se existir um grupo tem que estar nele pra locar.
Verifica se está em um grupo de uma unidade a cima, se sim pode locar.
Se não for nenhuma das demais não pode.
(futuramente poderá usar a permissão por e-mail do admin, mas agora não)

**Comment by gabrieltron** [comment]
concluido

**Comment by ramonrdm** [comment]
podemos criar uma ReservasAdmin e vai ser a classe mãe de ReservaEquipamentoAdmin e ReservaEspacoFisicoAdmin

**Comment by gabrieltron** [comment]
aqui ta feita a super classe das reservas
bd0e5da752ad007eed3d5e448e2ba90b8f7562ba
aqui aproveitei e fiz pra locavel também
d57d4ea1a418fb67c23347007e6b9f1a3f0254e9

**Comment by ramonrdm** [comment]
ok feito!
