### ISSUE TITLE
Antecedencia do agendamento [resevas.ccs]

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#2]
O Prof Celso também sugeriu que todos os agendamentos (de todos os espaços) possam ser feitos somente com uma antecedência de 6 meses ou semestralmente, pois muitas pessoas fazem agendamentos para o ano todo, e, muitas vezes, nem usam, prejudicando os outros.

**Comment by ramonrdm** [comment]
Penso que criar uma opção de dias de antecedência no espaço resolva.
default = 0 para sem limite ou inteiro positivo para dias de máxima antecedência.
Outro possível requisito seria para anos, tipo pode ser feito até o final desse ano ou até o final do ano que vem.

**Comment by ramonrdm** [comment]
Antecedência mínima e máxima, em dias, defaults 0

**Comment by gabrieltron** [comment]
feito b5ee798ea9cc6eaeeb39642c677c64c5c69f7e11

**Comment by ramonrdm** [comment]
Muito bom!
Agora me surgiu que o responsável do locavel poderia ser uma exceção, poderia colocar a antecedência que quisesse. Vamos colocar isso tbm?

**Comment by gabrieltron** [comment]
feito 228c60f533225d0d66b812eea5efbfd6dd17e142

**Comment by ramonrdm** [comment]
ok
