### ISSUE TITLE
Formulario de add locavel tem que preencher duas vezes.

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#20]

**Comment by gabrieltron** [comment]
Precisa preencher duas vezes pra ele realmente cadastrar? No servidor de teste parece ok

**Comment by ramonrdm** [comment]
Uehh eu testei e nao ia de primeira...

**Comment by gabrieltron** [comment]
parece que quando vai pelo intermediário ele tem que ser duas vezes, tanto que por ele o link do formulário não fica com o link do admin, acho que esse negócio da url pode ta relacionado

**Comment by gabrieltron** [comment]
e3e75ad6a92461f9627b1492f3071f5909b0f736
mandei um ajax pra atualizar as informações necessárias do request e depois redireciona direto pro adicionar reserva, desse jeito não passa por um link intermediário e funcionou. O javascript tá no html porque ele precisa de informações passadas pela view como o tipo do locavel pra redirecionar

**Comment by ramonrdm** [comment]
João seu mostro! parece que deu certo! Parabens!

**Comment by ramonrdm** [comment]
ok
