### ISSUE TITLE
aumentar tamando da sigla de unidade?

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#22]
to em duvida

**Comment by ramonrdm** [comment]
podemos deixar a sigla curta e mostra o nome completo a baixo qndo mostramos as unidades.

**Comment by ramonrdm** [comment]
sigla da unidade com 20 caracteres, mostrar o nome no header

**Comment by gabrieltron** [comment]
concluido 15254dc50c45d862e5cd1caaa8e43ef61af8e60a
