### ISSUE TITLE
mostrar imagem qndo não tem imagem

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#23]
qndo uma imagem de unidade, equipamento ou espaço não existir, mostrar um icone do materializecss

**Comment by gabrieltron** [comment]
concluido 63c9ab3925427fe4bd12edac7c0bf4934bd275d9

**Comment by ramonrdm** [comment]
porque nao usar um icon?

**Comment by gabrieltron** [comment]
3cb3ca04f819613917202427bb5f3d4f7d9c923d
