### ISSUE TITLE
filter unidades em unidades

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#28]
só ve unidade que é responsavel
ser for root ve tudo

**Comment by gabrieltron** [comment]
57b6201169844872aead28e285abb701cb2710b3

**Comment by ramonrdm** [comment]
coloquei um usuario como responsavel de uma unidade e na listagem dele apareceu outra unidade, verifique novamente o algoritmo

**Comment by gabrieltron** [comment]
e55beb13f23de6cedd3091849e9a3793f952d5fb

**Comment by ramonrdm** [comment]
agora sim!
