### ISSUE TITLE
Página do locavel

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#29]
todo locavel deve ter uma página mostrando suas características/informações.

**Comment by gabrieltron** [comment]
ff0887e263484b9bf9e22279fdc146e3de890ad3

**Comment by ramonrdm** [comment]
colocar uma margem do lado esquerdo do texto.
mas está ótimo!

Ramon Dutra Miranda - RDM

<http://RamonRDM.wordpress.com>

2017-12-08 14:23 GMT-02:00 gabrieltron <notifications@github.com>:

**Comment by gabrieltron** [comment]
f268a89f7e3388bc49751f628feab97286c7c587
