### ISSUE TITLE
Estudar funcionamento e código do Agendador

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#3]
Veja como está funcionando o reservas.ccs.ufsc.br e tente fazer reservas de espaços físicos.
Depois disso baixe o código e faça funcionar e sua máquina.
Utilize uma virtual env com py 2.7 e django 1.10

**Comment by ramonrdm** [comment]
e ai ? como estamos?

**Comment by antoniobesen** [comment]
Esqueci de fechar essa issue. Estamos na mesma de ontem, quando você saiu estava no fim do meu horário, instalei mysql, fiz funcionar, tinha um problema ao renderizar os templates, terminei e comecei a estudar o django materials. Hoje ainda não fiz nada, estou fazendo um trabalho, se der farei algumas horas aí mais tarde.
