### ISSUE TITLE
widget horas dentro de reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#30]
deve mostrar somente horas e não o calendário inteiro.
Seria interessante colocar de hora em hora ou nas horas de aula padrao ufsc.
atualmente mostra de horar em hora a partir da hora q no preenchimento, tipo 13:39 entao, 14:39, 15:39... assim fica ruim.

**Comment by gabrieltron** [comment]
cd7258fe13b920283f22d0f6895f136736d57cc6

**Comment by ramonrdm** [comment]
resolvido a tempos
