### ISSUE TITLE
Detalhamento da reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#31]
aparacer os grupos do usuário que fez a reserva.

**Comment by gabrieltron** [comment]
f268a89f7e3388bc49751f628feab97286c7c587

**Comment by ramonrdm** [comment]
legal colocar "Unidades" ou "Unidades do solicitante" no lugar de grupos.

**Comment by gabrieltron** [comment]
570f472789a474cfb2e8a66d5d822b2e0d9e6b06
deixei unidades do usuário, o campo de cima já diz 'Usuário' então achei mais fácil de enteder

**Comment by ramonrdm** [comment]
certo!
