### ISSUE TITLE
Pesquisar por locavel vago

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#34]
Dentro de cada unidade buscar por locável que esteja vago dentro das horas xx:xx até yy:yy e na data zz/zz/zzzz, opção de escolher o tipo do locável.

**Comment by ramonrdm** [comment]
Estou pensando em um formulário dentro da index, para aparecer dentro de todas as páginas de unidades, qndo pesquisado exibe uma nova lista de locáveis que satisfaçam as condições.
Fazer um novo form dentro do forms e então usar ele dentro da view.

**Comment by gabrieltron** [comment]
ffd1f2a5e72f6406e1cd2ea4177605d10ffc2a99

**Comment by ramonrdm** [comment]
funcionando.
mas precisa corrigir erro na pesquisa vazia.

**Comment by gabrieltron** [comment]
dfb387cecbece840c2e94bebe1f93e24801ed749

**Comment by ramonrdm** [comment]
preciso esta logado para reservar, o correto eh fazer mesmo nao logado.
qndo logado não esta mostrando todas as possibilidades, tipo soh mostra o que tenho acesso, mas a ideia desse filtro eh mostrar tudo.

**Comment by gabrieltron** [comment]
feito 26829ef2b92bfcb67f759d713529236514f50300

**Comment by ramonrdm** [comment]
certo!
