### ISSUE TITLE
atividades permitidas para reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#36]
Havia um equivoco, todo locável pode ter um conjunto de atividades permitidas e não somente o espaço físico, então subi isso para a classe abstrata locável.
Agora falta no form da reserva de equipamento e espaço físico coloca como pre-set somente as atividades permitidas do locável em questão.
desta forma a pessoa só poderá realizar reservas do que é permitido, exemplo locável auditório pode somente ter palestras e seminários, então o usuário não poderá solicitar uma reserva para dar aula neste local.

**Comment by gabrieltron** [comment]
e889c3141398a850096d3b12ebc86a87ebf8d800

**Comment by ramonrdm** [comment]
funcionando com ajax
