### ISSUE TITLE
sobre e "home" com menu principal e nao dentro de agenda....

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#39]
No menu principal o "site principal" deveria estar aparecendo na lista principal e não no submenu.
Para que desta forma em qualquer lugar do sistema o usuário possa voltar para a pagina inicial do sistema de forma fácil.

**Comment by AdrianoTosetto** [comment]
Menu atualizado:

https://github.com/ramonrdm/agendador/commit/c113a4a1fd098f390b23da6eab7bbde55361d565

**Comment by ramonrdm** [comment]
agora o item do menu chamado "agenda" ficou sem sentido, retire ele.
está ocorendo alguns erros, mas não sei se está ligado a estes commits.
a foto do equipamento ou unidade não está aparcendo e sim o icone de usuário.
