### ISSUE TITLE
menu responsivo com barra horizontal

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#40]

**Comment by gabrieltron** [comment]
O problema é o javascript, mesma coisa de quando o collapsible não abria. Parece que o javascript que precisa pro menu funcionar é justamente o que da conflito com elementos do materialize no index.

**Comment by gabrieltron** [comment]
936e479e4f390671e553fbc5961f1f564ed28543
okay era mais facil do que pensei antes aiwuelfalkwje

**Comment by ramonrdm** [comment]
ok
