### ISSUE TITLE
detalhes do locavel* mata o calendario

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#41]
qndo volta do detelhe da reseva mata o calendario.

**Comment by gabrieltron** [comment]
alguma condição específica pra isso acontecer? No servidor de teste parece ok. Vou colocar pra usar só os javascripts necessários ao invés de usar o super do material, já que é o que funcionou no index

**Comment by ramonrdm** [comment]
detalhes do locável*

**Comment by ramonrdm** [comment]
não acontece mais, deves ter corrigido o problema em alguma outra issue.
