### ISSUE TITLE
Estado da reserva não aparecer

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#42]
o estado da reserva não deve aparecer para usuários comuns só para admin.
depois vamos mudar isso, mas agora não precisa aparecer.

**Comment by gabrieltron** [comment]
ad366dbe8c5c4d77b56e1d7ffe57c2f592891bc6
Tenho uma ideia de como melhorar isso

**Comment by ramonrdm** [comment]
ta ok.
qual eh a ideia?

**Comment by gabrieltron** [comment]
Quando o estado é 'esperando' o usuário não vê o estado e pode editar o pedido, tipo hora e data. Depois de confirmado ou negado o pedido a pessoa pode ver o estado, mas ele e todos os outros campos são marcados como apenas leitura, para que o usuário não possa alterar data ou hora depois de já confirmado.

**Comment by ramonrdm** [comment]
Não seria mais facil, apenas verificar se é uma alteração e dizer que não pode fazer?
não pode alterar somente fazer uma nova.
acho que seria o suficiente.

**Comment by gabrieltron** [comment]
Achei que ficou legal assim
b3cf03e3746beacee782923d670f0a4d44003456
Pelo que entendi a ideia era tirar a permissão de editar do usuário pelo próprio django (não sei se entendi certo), mas isso é ruim porque o usuário fica impedido de acessar a parte de reserva do admin. Assim ele só bloqueia os campos e não deixa editar, aí o usuário continua podendo consultar as informações que ele preencheu caso seja necessário

**Comment by ramonrdm** [comment]
Acho que ficou legal tbm!
Parabéns!
:)
