### ISSUE TITLE
enviar email

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#44]
enviar email para ao solicitante da reservas confirmando a reserva se ela for efetuada automaticamente.
enviar email para o responsavel quando o solicitante não tem permissão automatica, enviar o link direto da reserva solicitada. Neste caso também envia um email ao solicitante para notificar que esta pendente. quando for autorizada avisa novamente.

**Comment by gabrieltron** [comment]
feito 0ec7af75c184e2f2559cf40399d46d468ae87ae8
O email com o link pra aprovar a reserva tá com o link do servidor de testes, na hora de botar no ar precisa trocar pela url do site. Pode ser assim ou já commitar com o link do site mesmo e mudar quando for testar?

**Comment by ramonrdm** [comment]
usa o base url do django mesmo, assim nao importa qual for o local que roda ele pega a url usada.

**Comment by gabrieltron** [comment]
Quando fui testar agora deu o seguinte erro: 
```
SMTPRecipientsRefused at /admin/agenda/reservaespacofisico/2/change/
{u'meu_email@hotmail.com': (553, '5.7.1 <reservas.ccs@sistemas.ufsc.br>: Sender address rejected: not owned by user reservas.ccs@sistemas.ufsc.br')}
```
Quando trabalhei no laboratório isso não acontecia, pelo que pesquisei é como se o endereço de e-mail utilizado pra enviar não existisse no configurado no settings, o que é estranho já que é o mesmo. Talvez possa ter a ver com não estar na rede da UFSC, VPN não está funcionando então não conseguir testar. Deixei o método que envia o e-mail comentado para garantir que não vai quebrar até descobrir isso

**Comment by ramonrdm** [comment]
Sim tem que estar dentro da UFSC.
Sugiro usar VPN, podes precisar liberar isso no roteador de internet.

**Comment by gabrieltron** [comment]
feito a596adfd6dff2490dc887c5b5b2f7409eb9b51ce

**Comment by ramonrdm** [comment]
ok
