### ISSUE TITLE
se criar uma unidade com espaço no nome da erro na index.

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#45]
tem que restringir no form colocar espaço, ou entao pode ser trocado por - ou _

**Comment by gabrieltron** [comment]
Acho que seria legal dar um jeito de trocar por '-' pra não limitar o usuário, mas não consegui pensar num jeito prático de manter a sigla como identificador no link e conseguir converter pra '-' e de '-' pra espaço, já que não tem como saber se o '-' do link era '-' ou espaço
De todo jeito coloquei pra não deixar sigla com espaço pelo menos por enquanto, que aí pelo menos ele não quebra
6c95c9ffab831e89c8b3a6e9fe0a814260ad541b

**Comment by ramonrdm** [comment]
sim por enquanto restringimos.
