### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#46]
update readme, put setup, venv, migrate, etc.

**Comment by AdrianoTosetto** [comment]
Readme atualizado:
https://github.com/ramonrdm/agendador/commit/97aa55b1d210b5d4c765eb6e84eebf12632f8a93

**Comment by ramonrdm** [comment]
fiz alguns comentarios no commit, ajuste eles.

**Comment by ramonrdm** [comment]
trocar
  $ git clone -b develop https://github.com/ramonrdm/agendador
por 
  $ git clone https://github.com/ramonrdm/agendador

pois o master eh quem garantimos um build sem falhas.

**Comment by AdrianoTosetto** [comment]
Se for trocar isso, tem que trocar os loaddata tb. Acho mais jogo deixar um readme pro master e um pro develop, o que você acha?

**Comment by ramonrdm** [comment]
Não, pois não garantimos que o develop vai funcionar entende.... se for um desenvolvedor que estiver mexendo e quer realmente estar no develop então ele vai saber fazer funcionar ou então precisa falar com a gente, pois o develop não eh versao fechada entende?

**Comment by AdrianoTosetto** [comment]
Entendi, então vou testar pra ver se funcionar o loaddata com auth.json e agenda.json no master

**Comment by ramonrdm** [comment]
toma cuidado que na versao 0.9.5 eu retirei os migrates, antes tinha alguns
arquivos, agora tem só um.

Ramon Dutra Miranda - RDM

<http://RamonRDM.wordpress.com>

2018-02-07 14:37 GMT-02:00 AdrianoTosetto <notifications@github.com>:

**Comment by ramonrdm** [comment]
tens que apagar teu banco e fazer migrate de novo.

Ramon Dutra Miranda - RDM

<http://RamonRDM.wordpress.com>

Em 7 de fevereiro de 2018 14:38, RAMON RDM <ramon.rdm@gmail.com> escreveu:

**Comment by ramonrdm** [comment]
ok
