### ISSUE TITLE
coluna de meses

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#47]
quem sabe ficasse mais interessante colocar locaveis e meses centralizados, segue a imagem.
![screenshot-2018-1-13 agendador - videoconferenciacce](https://user-images.githubusercontent.com/5952767/34906246-b3eebaca-f850-11e7-8e20-3a52b53f7fba.png)

**Comment by gabrieltron** [comment]
Desse jeito?
2494e239770afd1b1682f661fe4337fe1e25cd75
