### ISSUE TITLE
tratar falta do email de envio

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#52]

**Comment by gabrieltron** [comment]
1c4a2c1fd75d22c14b33e1cfddc4a23b72452587
ainda vou tentar ver como avisar o usuário

**Comment by gabrieltron** [comment]
agora foi 1b21d9d9114b5473fa65e1c5913c948f5745e65b

**Comment by ramonrdm** [comment]
perfeito com mensagens!
