### ISSUE TITLE
Reserva periódica/repetir

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#56]
poder colocar repetição de data x a data y no horario z.
atenção ao email para não enviar x a y e-mails ao usuário, condensar em um único e-mail neste caso.

se isso for feito fazer uma action na listagem de modelos para alterar do estado esperando para o estado aprovado, desta forma o admin pode aprovar uma serie de reservas de uma unica vez.

**Comment by ramonrdm** [comment]
criar uma classe período que tem onetomany de reservas, fazer view customizada para aprovar ou reprovar tudo.

**Comment by gabrieltron** [comment]
4a456c3eacbf48602445635525122b37b93330cc feito

**Comment by ramonrdm** [comment]
perfeito
