### ISSUE TITLE
erro ao fazer loaddata 

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#57]
django.db.utils.OperationalError: Problem installing fixture '/home/ramonrdm/agendador/agenda/fixtures/agenda.json': Could not load agenda.Unidade(pk=1): no such table: agenda_unidade

Descobrir porque esta dando esse erro e corrigir.

**Comment by ramonrdm** [comment]
python manage.py loaddata auth.json
ou 
python manage.py loaddata agenda.json
caem nesse erro.

**Comment by AdrianoTosetto** [comment]
Ramon, vc deu o migrate? Não consegui fazer esse erro aqui seguindo o q tá no readme. Eu fiz outra vez sem fazer migrate e ocorreu o seguinte erro: ```Could not load auth.Permission(pk=1): no such table: auth_permission```

**Comment by AdrianoTosetto** [comment]
Tu deu esses loaddata usando a branch master?

**Comment by ramonrdm** [comment]
Era isso mesmo! faltou o migrate, resolvido.
