### ISSUE TITLE
retirar a opoção alterar senha

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#58]
qndo logado dentro header canto direito.

**Comment by AdrianoTosetto** [comment]
commit: https://github.com/ramonrdm/agendador/commit/3120b1c571c1855e00d1b9ad553d370caa9202e5

**Comment by ramonrdm** [comment]
O commit tem alguns problemas, você deve descartar esse commit, pelo menos no que diz respeito a mexer o django-material

**Comment by AdrianoTosetto** [comment]
Eu pensei que tinha que sobrescrever o bloco, mas onde eu faria isso? Nos outros lugares no projeto, tinha um arquivo dando um extends em algum arquivo material, mas no admin não encontrei isso. Então mudei direto no material.

**Comment by ramonrdm** [comment]
acho que da pra fazer assim, tu copia o template do material pra dentro do agenda/templates/admin/ e edita ele ali, dessa forma ele deve sobre escrever. Me incomoda ter que alterar o codigo original, mas pelo menos nesse caso não estamos alterando na biblioteca e sim dentro do nosso app.

**Comment by AdrianoTosetto** [comment]
commit: https://github.com/ramonrdm/agendador/commit/f7f063cf31747bf0ad45eba83f9e842ea09cc303

**Comment by ramonrdm** [comment]
ok
