### ISSUE TITLE
link direto para o locavel

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#61]
Hoje não consigo enviar um link direto do locável, sem que tenha um mês, como:
https://reservas.cce.ufsc.br/mes/f/10
No antigo havia uma url e a view mes tratavam essa possibilidade, precisamos disso novamente.

**Comment by ramonrdm** [comment]
a ideia eh que ao entrar no link apareça o mês atual, dessa forma se o link for disponibilizado no em um site, ficará sempre no mês atual.

**Comment by gabrieltron** [comment]
feito 4b26fc7236c6dd35cdb9d9d5f838d7c65fd30280
link é /locavel/tipo-do-locavel/id-do-locavel/reservas

**Comment by ramonrdm** [comment]
porque não fazer somente /mes/tipo-locavel/id-locavel ?
pode ser tratado isso na view mes.

**Comment by gabrieltron** [comment]
feito 4c300c715c3a9aea38a8db27dadf55005d527777

**Comment by ramonrdm** [comment]
certo
