### ISSUE TITLE
Como reservar somente com autorização do responsavel

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#62]
Digamos que tenha um locavel que o responsavel quer sempre aprovar ou não a reserva, como poderiamos fazer isso com a implementação atual? senão é possível então o que precisamos fazer para realizar isso?

**Comment by ramonrdm** [comment]
É responsabilidade dos dois dar a solução.

**Comment by gabrieltron** [comment]
Colocar mais um campo no modelo parece muita coisa, pensei em talvez só um novo field no form que se marcado ele já cria um grupo e deixa o locavel nele. O problema disso é que isso vai aparecer nos "grupos" em detalhes do locável, mas deve ter algum jeito de diferenciar esse grupo dos demais e não listar ele

**Comment by ramonrdm** [comment]
Uma solução viável, mas não parece orgânica ao sistema, não parece natural, vamos ter que fazer varias checagens.
Pensei em quebrar a hierarquia que fizemos até agora, se não houver grupo tem que autorizar via email, atualmente ele herda as permissões da unidade de cima. Neste caso toda unidade ou locavel teria que explicitar seus grupos, se não fizer será autorizado por email.
continua sendo uma analise nao a solução final.

**Comment by ramonrdm** [comment]
usar uma flat no model locavel, label "Reservar somente com autorização do responsável"

**Comment by ramonrdm** [comment]
feito.
