### ISSUE TITLE
Django se comporta diferente para cada dominio

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#63]
Fazer com que o Django reconheça e reaja a cada dominio, exemplo, reservas.cce.ufsc.br e reservas.ccs.ufsc.br, em cada caso ele mostra não a página principal mas a página da referida unidade.

**Comment by gabrieltron** [comment]
feito b7aab4b689e13c8d062a18265b76bc929449496e

**Comment by ramonrdm** [comment]
ok vamos testar em voo
