### ISSUE TITLE
Versão mobile do form reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#64]
o horario ta bem ruim, não consigo escollher.

**Comment by gabrieltron** [comment]
8d8af59783f9158d5ab11a9efc319c1d4b2cd295
O comportamento parece diferente no teste do chrome/firefox e em celulares realmente. Testando no modo de teste de mobile do firefox não está funcionando, mas usando o servidor de teste e usando no celular mesmo dá certo.
Eu acredito que seja pela ação no javascript, tive alguns problemas com a diferença entre ações como "mousedown" e "touchstart", talvez no ambiente de teste ele considere os dois e cause problemas.
De todo jeito no celular mesmo tá bem topíssimo

**Comment by gabrieltron** [comment]
Além disso ele só ativa quando em mobile, então a versão de computador mesmo continua igual

**Comment by ramonrdm** [comment]
vamos testar em voo

**Comment by ramonrdm** [comment]
ainda ha problemas, mas consigo reservar.
vamos verificar como ficará no futuro com a versao dj 2.x
