### ISSUE TITLE
importar calendarios a outros sites

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#65]
Preciso de uma view que possa ser incorporada em outros site, exemplo colocar o calendario de um laboratorio dentro do páginas UFSC. seria algo como incorporar o html dentro de outra página.

**Comment by AdrianoTosetto** [comment]
Podes me dar um exemplo mais concreto?
seria tipo:
```
def view_calendario():
     cria_calendario()
```
?

**Comment by ramonrdm** [comment]
como aqui:
http://www.videoconferencia.cce.ufsc.br/index.php?option=com_gcalendar&view=gcalendar&Itemid=2#year=2018&month=2&day=7&view=month
eh uma agenda externa incorporada dentro de uma página.

**Comment by AdrianoTosetto** [comment]
commit: https://github.com/ramonrdm/agendador/commit/7b30c9f89893f12299b5a0a7a72e55d100911e7a

**Comment by ramonrdm** [comment]
ok funcionando!
