### ISSUE TITLE
erro responsavel tentando editar uniadade

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#66]
considere a versão master.

Request Method: | POST
-- | --
http://reservas.cce.ufsc.br/admin/agenda/unidade/8/change/
1.10.1
KeyError
'responsavel'
/var/www/html/agendador/agenda/forms.py in save, line 320
/usr/bin/python
2.7.14
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/var/www/html/agendador']
Seg, 19 Fev 2018 14:29:22 +0000

**Comment by gabrieltron** [comment]
354473775e660b4b514489d1046f1e1bc85bdccb
Agora funcionando. Por algum motivo responsáveis tava como readonly aí não tinha o que o form ler pra fazer aquela validação de grupos.

**Comment by ramonrdm** [comment]
ok
