### ISSUE TITLE
responsavel não consegue deletar reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#67]
Request Method: | GET
-- | --
http://reservas.cce.ufsc.br/admin/agenda/reservaespacofisico/
1.10.1
OperationalError
(1242, 'Subquery returns more than 1 row')
/usr/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 50
/usr/bin/python
2.7.14
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/var/www/html/agendador']
Ter, 20 Fev 2018 11:38:00 +0000

**Comment by gabrieltron** [comment]
c1664044aa431b453574c9fc16676f6d0f5f0717
Não consegui reproduzir o erro. Dei uma procurada no que pode causar ele e ajeitei o que parecia ser o problema

**Comment by ramonrdm** [comment]
ok
