### ISSUE TITLE
FAQ/Instruções

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#68]
Vamos criar uma area de instruções, seria um link junto com o "site principal" e "sobre".
Link: FAQ/Instruções
estou pensando em usar o sistema de páginas dinâmicas do Django.
Primeiras instruções:

Como fazer uma reserva.
    - Permissões
    - grupos 
    - Tipos de Locaveis
O que são unidades, locáveis, atividades, reservas.
Como configurar um locáveis, setar grupos, e permissões.

**Comment by gabrieltron** [comment]
893d2a3d80e22c9ab70dbb355ff05772dd92bd52
foi a estrutura pra criar o faq/instruções, ainda precisa criar as flatpages
ainda precisa definir todos os tópicos do faq, criar um json pra importar eles no servidor e criar um jeito de buscar no faq

**Comment by gabrieltron** [comment]
7c420932ae93182c709ae1099485848813b46518 filtro pra buscar no faq

**Comment by gabrieltron** [comment]
656b30e4a63c4ee2c317c8cf20f62fac895b14a1 foi algumas, tem que ver se precisa de mais

**Comment by ramonrdm** [comment]
ok, nao vou fechar pois vamos criar mais coisas.

**Comment by ramonrdm** [comment]
feito, deve ser atualizado ao longo do tempo
