### ISSUE TITLE
Definição de permissoes 

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#69]
Temos que definir os niveis de permissão
Usuario sem grupo
 - Precisa de aceite do responsavel
Usuario dentro de grupos
 - Tem autorização de reservar o espaço está no grupo do espaço
Responsaveis de locaveis
- Pode marcar reservas no seu locavel
- Pode controlar seu locavel, editar dados.
Responsaveis de unidades
 - Pode criar unidades ou locaveis a baixo das suas unidades
SuperUser 
+Faz tudo

Esboço... me ajudem a definir mais coisas rapazes.

**Comment by gabrieltron** [comment]
coloquei um guia assim em permissões no faq nesse commit aqui 656b30e4a63c4ee2c317c8cf20f62fac895b14a1

**Comment by ramonrdm** [comment]
Feito e vamos atualizando
