### ISSUE TITLE
Criar um grupo parar autorizar reservar automaticamente

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#70]
Para resolver alguns problemas pensei no seguinte:
toda vez que um usuário é criado no sistema ele vai entrar no grupo "allowed reservation" para que assim receba as permissões mínimas de para realizar o pedido de reserva, que será enviado por e-mail.
Desta forma o novo usuário não será bloqueado ao tentar fazer uma reserva, isso esta frustrando muito os usuários.
tbm fazer uma verificação se o grupo ja existe ou não.
estou em duvida onde colocar essa função, mas sei onde sera chamada, quem cria o usuário eh django_cas_ng/backends.py, def authenticate na class CASBackend (perto da linha 322)

**Comment by gabrieltron** [comment]
feito 23e68f23ffabc901743ff7e0590ae40dadd6d1e2

**Comment by ramonrdm** [comment]
funciona, porem esta no local incorreto, tanto que isso nao aparece na versao dev.
Criar um signals no projeto e passar as funções criadas em backends para o signals.

**Comment by gstvob** [comment]
o commit que eu adicionei resolveu. Feito da forma que tu falou, colocar uma função que é receiver do sinal post_save do modelo User do django.auth

**Comment by ramonrdm** [comment]
funcionando de acordo.
