### ISSUE TITLE
o calendario está escondendo a ultima linha

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#72]
venho notando que o calendario da reserva esta sempre escondendo a ultima linha do calendario em uma tela widescreen. verifique se temos como melhorar isso, afim de evitar que o usuários fique dando scroll.

**Comment by gabrieltron** [comment]
mudar a altura não parece muito bom, fica apertado o espaço que mostra as reservas. mudar a largura não mudou muito

**Comment by gabrieltron** [comment]
se pa assim 975b0326ef909d563b6c9b4dc7cebf0984eccb3c

**Comment by ramonrdm** [comment]
perfeito.
