### ISSUE TITLE
icon do sistema deve ser a logo da ufsc

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#74]

**Comment by gabrieltron** [comment]
6ff46ad674097a49b8faf614a141d116dc9e3750 feito

**Comment by gabrieltron** [comment]
não vi que não ta usando a pasta de media, agora foi usando links aiwejfaw
1dadcfbf32f1b117fd69cd95ce75ec49a5fad5d0

**Comment by ramonrdm** [comment]
ok
