### ISSUE TITLE
opções de edição e add form reserva

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#75]
opções de edição e add nao devem aparecer parar usuário normais, somente para admin e responsaveis. isso causa confusão nos usuários.
![whatsapp image 2018-02-28 at 12 15 51](https://user-images.githubusercontent.com/5952767/36795398-b81058fc-1c81-11e8-82ef-56bf2cc0ff20.jpeg)

**Comment by gabrieltron** [comment]
4dfbe19892c041a43d3454c9431bae109b671391 feito

**Comment by ramonrdm** [comment]
feito.
