### ISSUE TITLE
fixture do auth cria permissões erradas

### ISSUE THREAD

**Issue by gabrieltron** [ramonrdm/agendador#78]
Precisa deixar ela de lado, criar outra limpra pra pegar as permissões, e substituir as permissões na fixture

**Comment by gabrieltron** [comment]
5d4ad0ad75706da0e53947475b7fdb573c154004

**Comment by ramonrdm** [comment]
ao que parece sempre tem que fazer uma nova. 
pode dar conflito dependendo como o projeto recebe alterações.
