### ISSUE TITLE
Limitar o acesso do usuário as unidades que ele é responsavel

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#8]
isso pode ser filtrado dentro do admin.py onde se limita as unidades visualizadas para somente as que o usuário pertence como responsável.
Essa mesma lógica é aplicada aos equipamentos.
Isso não é pra reservar e sim para gerenciar(crud) unidades, espaços e equipamentos.

**Comment by ramonrdm** [comment]
Exemplo de filtragem no admin.py, dentro da nova classe admin q deves ser usada.
	
def get_queryset(self, request):
		qs = super(ChecklistAdmin, self).get_queryset(request)
		if request.user.is_superuser:
			return qs
		CTFilter = Comunidade.objects.filter(representante=request.user)
		return qs.filter(ct=CTFilter)

admin.site.register(Checklist, ChecklistAdmin)

**Comment by antoniobesen** [comment]
@ramonrdm Commitei com o usuário acessando apenas as unidades/equipamentos/espaço fisico na qual ele é responsável. Os fields 'responsável' e 'unidade' estão como read only para esses usuarios responsaveis. Caso deva deixar mais fields ou tirar esses fiends de read only me avise.
