### ISSUE TITLE
locavel de Serviço

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#81]
atribuir responsaveis pela execução do serviço

**Comment by gabrieltron** [comment]
2af968347d9d1571d08aec686c0c222a035f04b8 feito

**Comment by gabrieltron** [comment]
ainda precisa mudar os testes pra testar serviço também

**Comment by ramonrdm** [comment]
Gustavo confere os testes se estão verificando pra serviço.

**Comment by gstvob** [comment]
Bom, pelo o que eu olhei aqui, todos os testes fazem algo com serviço, não sei se precisa de algo especifico pra serviços.
