### ISSUE TITLE
verbose name dos fields

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#82]
fields da classe:
email = models.EmailField(verbose_name='E-mail')
e para a classe:
class Meta:
		verbose_name = 'modelo'
		verbose_name_plural = 'modelos'

**Comment by gabrieltron** [comment]
feito 0db8988ca3e6dfffe29aef326b89fd034b228dcc

**Comment by ramonrdm** [comment]
feito tem outros problemas com as label, mas esta em outra iissue
