### ISSUE TITLE
responsavel nao consegue editar unidade

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#83]
bug no fluxo:
Responsável tem uma unidade apenas, sendo assim a unidadePai não é dele e ele não pode criar unidade a baixo da dele. Por fim ao editar sua unidade ele não pode atribuir unidadePai a unidade superior como esta anteriormente.

**Comment by ramonrdm** [comment]
a ideia é permitir que o responsavel mantenha a unidadePai setada anteriormente, seria uma exceção no query do field.

**Comment by gabrieltron** [comment]
feito 8147ddfbb9de7aeaefc56cafec95e0f59b10533c

**Comment by ramonrdm** [comment]
perfeito
