### ISSUE TITLE
lista de reservas filtro estado

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#84]
Criar um filtro na lista de reservas para escolher o estado da reserva.

**Comment by gabrieltron** [comment]
feito 8205b73e5a56e330f580a28e2fbf437117aa3f48

**Comment by ramonrdm** [comment]
na verdade nao era pra filtrar com a pesquisa, eh pra um filtro que aparece do lado que vc seleciona e mostra somente os que tem aquela opção.

**Comment by gstvob** [comment]
tá la

**Comment by ramonrdm** [comment]
resolvido e funcionando.
apenas fechando a issue.
