### ISSUE TITLE
algumas fotos estão invertidas

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#88]

**Comment by gabrieltron** [comment]
1eb86a6abd8d41fcedd5baf0829f20ae4074da43
feito no firefox. vou continuar dando uma olhada, mas ao que parece outros navegadores não tem muito jeito

**Comment by ramonrdm** [comment]
Essa issue pode ser fechada, pois vamos deixar a cargo do usuário enviar a foto adequada.

**Comment by ramonrdm** [comment]
feito
