### ISSUE TITLE
Avisar ao responsavel de outra reserva no mesmo horario 

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#94]
Avisar ao responsável de outras reservas(não aprovadas) no mesmo horário quando ele esta aprovando uma reserva.
Pois os responsáveis podem aprovar de 10 pedidos somente o ultimo sem ver.
Pensei que seria interessante na hora de aprovar uma reserva ele receber essa mensagem na tela.

**Comment by gabrieltron** [comment]
anotação pra eu mesmo: lembrar o caso em que uma mensagem já está aberta pois a reserva é recorrente

**Comment by gabrieltron** [comment]
8ac92d960423b1be15b649f1ec49b4324a31ceea

funcionando para reservas não recorrentes

**Comment by gabrieltron** [comment]
feito 
7d418dd10125ae7f76ded0ad06710211b4d1cbd3

**Comment by ramonrdm** [comment]
funcionando
