### ISSUE TITLE
Não pode existir atividade com nome repetido.

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/agendador#98]

**Comment by ramonrdm** [comment]
no aviso de erro no form avisar que ja existe uma outra atividade com o mesmo nome e aquela deve ser usada a ja existente.

**Comment by gstvob** [comment]
feito aquilo que a gente tinha conversado

**Comment by ramonrdm** [comment]
Não consigo editar a descrição.
Deve ser tratado a possibilidade de estar editando e se o id bater com o que está o banco, não ha duplicidade e então pode ser salvo novamente.

**Comment by ramonrdm** [comment]
funcionando
